spring.application.name=Desafio03-DWF

# Configuracion de base de datos MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/sistema_reservas
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuracion de JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Configuracion de Swagger/OpenAPI (Acceso en /swagger-ui/index.html)
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

#Variables para el JWT
jwt.secret=ClaveUltraSecretaParaDWF2024Segura256Bits
jwt.expiration=86400000
jwt.refresh-expiration=604800000

